### ISSUE TITLE
Clicking Teleporter Does Nothing

### ISSUE THREAD

**Issue by Danickar** [henkelmax/advanced-mining-dimension#14]
**Please read the [FAQ](https://modrepo.de/minecraft/mining_dimension/faq) before submitting a bug report!**

**Bug description**
In single player everything seems fine. When on the server right clicking on the teleporter block does nothing.

**Versions**
- Minecraft version 1.16.3
- Forge version 34.1.1
- Mod version 1.0.4

I am not getting any errors thrown to really try and track down the cause that way.

**Comment by henkelmax** [comment]
Please add the logs of your server and client to this issue report.

**Comment by henkelmax** [comment]
Also please try if it happens with version 1.0.5
https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension/files/3074922

**Comment by Danickar** [comment]
[Server](https://pastebin.com/1hxZ8ihB)

Having an issue with client log (it is getting spammed with something not related to this mod that is causing issues bringing it up)

**Comment by henkelmax** [comment]
Have you ever restarted the server after having this issue.
In 1.16 there is a bug that custom worlds first load after the server was started a second time. 
If there is currently no `dimensions` folder inside your world folder, this might be the problem.

**Comment by Danickar** [comment]
I restarted the server twice (checking to see if configs change etc) with no effect. There is a dimensions folder in the world folder. Inside that is a folder for immersive_portals, but not one for mining.

**Comment by henkelmax** [comment]
Have you started the server before the mod was installed?

**Comment by Danickar** [comment]
Yes, it was a currently running server (about a week or so)

**Comment by henkelmax** [comment]
That may be the issue. Can you try running this mod on a fresh server?
If it works just copy the dimension to the old server.

**Comment by lordcovale** [comment]
Hi @henkelmax 

I love your mod, but I am also having this same occurrence. I have tried the steps you suggested to @Danickar 

Hopefully I can aid in narrowing down the issue, Current information 
Minecraft 1.16.3
forge 34.1.0
Mod 1.0.5

No errors in server log when clicking on mod block

Any data or logs that may be helpful
[debug-1.log](https://github.com/henkelmax/advanced-mining-dimension/files/5373200/debug-1.log)
?

**Comment by henkelmax** [comment]
This is a Minecraft/Forge bug, but it only occurs with custom dimensions in Forge mods.

> I copied the "dimensions" folder from the locally ran world to the server world. I'm now able to join the dimension.

https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension?comment=358

That is the current workaround.

**Comment by ProsperCraft** [comment]
Our mining dim worked great until we updated to mining_dimension-1.16.3-1.0.6.

The dim created fine previously.

**Comment by henkelmax** [comment]
Does it show the message?

**Comment by ProsperCraft** [comment]
Yes, it did

**Comment by henkelmax** [comment]
Did or does?

**Comment by CaptainAether** [comment]
I have this issue, I did the fix, I still get the "The Mining Dimension hasn't been created yet" message.

**Comment by henkelmax** [comment]
What exactly did you do?

**Comment by CaptainAether** [comment]
We moved from a Singleplayer LAN server to a hosted server, Copied over the world file, and the mining dimension stopped working, giving us that error instead. We clicked the link which brought us here, so we tried reuploading the dimensions folder, no good. We made an entirely new world and uploaded that one too, no good. One of our guys even tried moving the contents of the dimension up one level, no good.

**Comment by henkelmax** [comment]
I'm sorry, that the fix doesn't work for you, but there's nothing that I can do. It's a vanilla Minecraft bug.

**Comment by CaptainAether** [comment]
We will do that. Thank you for at least trying to help. Shame you cant do anything, but its good to know we tried.

**Comment by henkelmax** [comment]
This issue should now be fixed with https://github.com/MinecraftForge/MinecraftForge/pull/7445.
So if you run Forge 35.0.15 or newer, it should just work.

**Comment by MachinegunMarty** [comment]
Just wanted to say:

I'm running:
forge-35.0.15 and 
Mining World 1.16.4-1.0.1

I have an existing 1.16.4 world and added the latest advanced mining dimension.
If i place the teleporter i still get the message: The mining Dimension hasn't been created yet.

This is on an existing world.

**Comment by OoLunar** [comment]
Alright, so from what I understand, all we have to do is update our Forge version to 35.0.15+. That would involve bumping our MC version from 1.16.3 and below to 1.16.4. Some of our mods haven't updated from 1.16.3 to 1.16.4. I tried copying a local copy of the dimensions folder into the server world folder. No dice. What are we supposed to do?

**Comment by henkelmax** [comment]
Almost every 1.16.3 mod is compatible with 1.16.4. https://github.com/MinecraftForge/MinecraftForge/commit/160f3f88f9e540c86f788b55f5a11dffe9a79a1d

**Comment by predundant** [comment]
We're still having this issue on 1.16.5 with Forge 36.0.40, and version 1.16.5-1.0.2 of the mod.  

When we right click the portal block the loading screen comes up, but it just hangs there until the player closes the client.  Single player works as expected, the issue only occurs on the server.  Let me know if you need additional info.

Thanks

**Comment by henkelmax** [comment]
Please send me your logs. Also try it without any datapacks or other mods.

**Comment by SirOMGitsYOU** [comment]
> Please send me your logs. Also try it without any datapacks or other mods.

[logs.zip](https://github.com/henkelmax/advanced-mining-dimension/files/6032382/logs.zip)

**Comment by henkelmax** [comment]
I am not able to reproduce this issue. Please make sure you have no mods on your client and server and send me the logs again.

**Comment by SirOMGitsYOU** [comment]
> I am not able to reproduce this issue. Please make sure you have no mods on your client and server and send me the logs again.

The logs I sent were using our current mod setup where right-clicking the portal doesn't do anything - I don't know if it's because we're using - https://github.com/IzzelAliz/Arclight instead of normal forge

**Comment by henkelmax** [comment]
Sorry, but I only support forge. I can't guarantee that it works with such stuff.

**Comment by AirplanegoBrr** [comment]
I cant fix this too!
Using forge 36.1.0 for both server and client (I think? I know the client is)
![image](https://user-images.githubusercontent.com/71111395/114333346-efc47d80-9afc-11eb-9c42-e6f2199ab159.png)
![image](https://user-images.githubusercontent.com/71111395/114333362-f9e67c00-9afc-11eb-9c0a-1489409aecb3.png)
I even went to the same cords in the overworlded and placed the mining dim then moved it to my server not still not working! Anyone have any ideas????

**Comment by supersleepers** [comment]
Hi, I know this is an old thread, but I'm also getting this error when I try and use the portal on 1.16. I am using the default datapack, but with the default block changed to a modded block. ive tried a few modded blocks and it seems to only accept vanilla ones for the the default block.
